[package]
name = "onebrain-core"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
authors.workspace      = true
repository.workspace   = true
publish.workspace      = true

[dependencies]
serde          = { workspace = true }
serde_yaml     = { workspace = true }
serde_json     = { workspace = true }
thiserror      = { workspace = true }
chrono         = { workspace = true }
regex          = { workspace = true }
indexmap       = { workspace = true }
onebrain-token = { workspace = true }
sha2           = { workspace = true }

[dev-dependencies]
tempfile          = { workspace = true }
pretty_assertions = { workspace = true }
insta             = { workspace = true }
